name: Multi-Distro KVM Images Builder

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build-kvm-images:
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        distro: ["debian", "ubuntu", "fedora", "opensuse", "alpine", "archlinux", "centos", "almalinux", "rockylinux", "oracle"]
        arch:
          - name: amd64
            runner: ubuntu-latest
          - name: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.arch.runner }}
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v4

    - name: Check workspace
      run: pwd

    - name: Build environment
      run: |
        sudo apt update -y
        sudo apt install -y polkit || sudo apt install -y policykit-1
        sudo apt install -y jq btrfs-progs dosfstools qemu-kvm
        
    - name: Configure Git Identity
      run: |
        git config --global user.name "daily-update"
        git config --global user.email "tg@spiritlhl.top"

    - name: Build and Upload KVM Images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set +e
        DISTRO="${{ matrix.distro }}"
        ARCH="${{ matrix.arch.name }}"
        echo "Processing $DISTRO for $ARCH architecture"
        echo "---zip_name_list---"
        output=$(bash build_kvm_images.sh $DISTRO false $ARCH | tail -n 1)
        zip_name_list=($output)
        echo "---zip_name_list---"
        for item in "${zip_name_list[@]}"; do
          echo "$item"
        done
        echo "-------"
        release_response=$(curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/oneclickvirt/incus_images/releases/tags/kvm_images" || true)
        if [ "$(jq -r '.id' <<< "$release_response")" == "null" ]; then
          echo "Creating new release for kvm_images"
          release_response=$(curl -sS -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"tag_name":"kvm_images", "name":"KVM Images", "generate_release_notes":true}' \
            "https://api.github.com/repos/oneclickvirt/incus_images/releases" || true)
        fi
        release_id=$(jq -r '.id' <<< "$release_response")
        echo "Building $DISTRO KVM images and packaging zips for $ARCH"
        sudo bash build_kvm_images.sh $DISTRO true $ARCH || true
        echo "------------"
        pwd
        ls
        echo "------------"
        for file in "${zip_name_list[@]}"; do
          if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485760 ]; then
            echo "Processing $file (size: $(numfmt --to=iec-i --suffix=B $(stat -c %s "$file")))"
            asset_name=$(basename "$file")
            existing_asset=$(curl -sS -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets" \
              | jq -r --arg name "$asset_name" '.[] | select(.name == $name)')
            if [ -n "$existing_asset" ]; then
              asset_id=$(jq -r '.id' <<< "$existing_asset")
              echo "Removing existing asset ID $asset_id"
              curl -sS -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                "https://api.github.com/repos/oneclickvirt/incus_images/releases/assets/$asset_id" || true
            fi
            echo "Uploading $asset_name..."
            curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              --data-binary @"$file" \
              "https://uploads.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets?name=$asset_name" || true
            sudo rm -vf "$file"
          else
            echo "Skipping $file - does not exist or size <10MB"
            [ -f "$file" ] && rm -vf "$file"
          fi
        done
      continue-on-error: true