name: test images

on:
  schedule:
    - cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  test_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: check path
      run: |
        pwd

    - name: build environment
      run: |
        apt-get install -y btrfs-progs
        export noninteractive=true
        curl -L https://raw.githubusercontent.com/oneclickvirt/incus/main/scripts/incus_install.sh -o incus_install.sh
        chmod +x incus_install.sh
        bash incus_install.sh
        
    - name: test images
      run: |
        chmod 777 test.sh
        sudo bash test.sh
        
    - name: Configure Git
      run: |
        git config --global user.name "daily-update"
        git config --global user.email "tg@spiritlhl.top"
      
    - name: Add files to Git staging area
      run: |
        ls
        pwd
        git add .
        
    - name: Check Git status
      run: |
        git branch -a
        git remote -v
        git status
    
    - name: Commit changes
      run: |
        git commit -m "Update files" | true
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
