name: Test Incus Images

on:
  schedule:
    - cron: '0 4 2-30/2 * *'
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          # 下载两个平台的镜像列表
          curl -o x86_64_all_images.txt https://raw.githubusercontent.com/oneclickvirt/incus_images/main/x86_64_all_images.txt
          curl -o arm64_all_images.txt https://raw.githubusercontent.com/oneclickvirt/incus_images/main/arm64_all_images.txt
          
          echo "构建测试矩阵..."
          matrix_json="{\"include\":["
          
          while IFS= read -r image; do
            if [[ -n "$image" ]]; then
              matrix_json+="{\"image\":\"$image\",\"arch\":\"amd64\",\"runner\":\"ubuntu-latest\"},"
            fi
          done < x86_64_all_images.txt
          
          while IFS= read -r image; do
            if [[ -n "$image" ]]; then
              matrix_json+="{\"image\":\"$image\",\"arch\":\"arm64\",\"runner\":\"ubuntu-24.04-arm\"},"
            fi
          done < arm64_all_images.txt
          
          # 去掉最后一个逗号
          matrix_json=${matrix_json%,}
          matrix_json+="]}"
          
          echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"

  test-single-image:
    needs: prepare-matrix
    name: test-${{ matrix.image }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 8
    outputs:
      test_result: ${{ steps.test.outputs.test_result }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fresh Environment
        run: |
          echo "设置新环境..."
          sudo apt-get update -y
          sudo sh -c 'export DEBIAN_FRONTEND=noninteractive && curl -L https://raw.githubusercontent.com/oneclickvirt/incus/main/scripts/incus_install.sh -o incus_install.sh && chmod +x incus_install.sh && bash incus_install.sh'
      - name: Configure Git
        run: |
          git config --global user.name "daily-test"
          git config --global user.email "test@spiritlhl.top"
      - name: Test Image
        id: test
        continue-on-error: true
        run: |
          echo "测试镜像: ${{ matrix.image }}"
          # 备份 DNS 配置
          sudo cp /etc/resolv.conf /etc/resolv.conf.backup || true
          
          if sudo bash test.sh "${{ matrix.image }}"; then
            echo "测试通过: ${{ matrix.image }}"
            # 将结果写入文件
            mkdir -p ./results
            echo "{\"success\":true,\"image\":\"${{ matrix.image }}\",\"arch\":\"${{ matrix.arch }}\"}" > "./results/result-${{ matrix.image }}.json"
            echo "test_result=success" >> "$GITHUB_OUTPUT"
          else
            echo "测试失败: ${{ matrix.image }}"
            echo "{\"success\":false,\"image\":\"${{ matrix.image }}\",\"arch\":\"${{ matrix.arch }}\"}" > "./results/result-${{ matrix.image }}.json"
            echo "test_result=failure" >> "$GITHUB_OUTPUT"
          fi
          # 还原 DNS 配置
          sudo mv /etc/resolv.conf.backup /etc/resolv.conf || true
      
      - name: Upload Test Result
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: result-${{ matrix.image }}
          path: ./results/result-${{ matrix.image }}.json

  results-updater:
    needs: test-single-image
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Results
        uses: actions/download-artifact@v3
        with:
          path: ./results
      
      - name: Aggregate Test Results
        run: |
          # 初始化结果文件
          > x86_64_fixed_images.txt
          > arm64_fixed_images.txt
          
          echo "聚合测试结果..."
          for result_file in $(find ./results -name "*.json"); do
            if [[ -f "$result_file" ]]; then
              # 使用jq解析JSON文件
              if [[ -x "$(command -v jq)" ]]; then
                success=$(jq -r '.success' "$result_file")
                image=$(jq -r '.image' "$result_file")
                arch=$(jq -r '.arch' "$result_file")
              else
                # 如果没有jq，使用grep和sed解析JSON
                success=$(grep -o '"success":\(true\|false\)' "$result_file" | sed 's/"success"://')
                image=$(grep -o '"image":"[^"]*"' "$result_file" | sed 's/"image":"//;s/"//')
                arch=$(grep -o '"arch":"[^"]*"' "$result_file" | sed 's/"arch":"//;s/"//')
              fi
              
              echo "处理结果: success=$success, image=$image, arch=$arch"
              
              if [ "$success" = "true" ]; then
                if [ "$arch" = "amd64" ]; then
                  echo "$image" >> x86_64_fixed_images.txt
                elif [ "$arch" = "arm64" ]; then
                  echo "$image" >> arm64_fixed_images.txt
                fi
              fi
            fi
          done
          
          echo "排序去重..."
          sort -u x86_64_fixed_images.txt -o x86_64_fixed_images.txt
          sort -u arm64_fixed_images.txt -o arm64_fixed_images.txt
          
          echo "最终结果："
          echo "成功的 x86_64 镜像："
          cat x86_64_fixed_images.txt
          echo "成功的 arm64 镜像："
          cat arm64_fixed_images.txt

  cleanup:
    needs: results-updater
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "所有测试完成。请查看 Actions 页面获取详细测试结果。"
